build_script:
  - git status

artifacts:
  - path: '**\*.*'


deploy:
  provider: FTP 
  protocol: sftp
  host: 60.205.191.214 
  username: root
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
  password: xzxloveldn910208
  active_mode: false 