build_script:
  - git status

artifacts:
  - path: '*.md'
    type: file
    name: app


deploy:
  provider: FTP 
  protocol: ftp
  host: 60.205.191.214 
  username: webftp
  Artifact: app
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
  password: 
    secure: PSTgzcogMszFKm0drUJ6eA==
  active_mode: false 