build_script:
  - git status

artifacts:
  - path: '**\*.*'


deploy:
  provider: FTP 
  protocol: sftp
  host: 60.205.191.214 
  username: root
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
  password: 
    secure: yEY1gj7tDDldcendeCe3SU6h697tct4gge3PCr7apHk=
  active_mode: false 